name: aplicativo_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.1.0
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  cloud_functions: ^6.0.4
  firebase_storage: ^13.0.4
  google_fonts: ^6.3.2
  auto_size_text: ^3.0.0
  http: ^1.5.0
  youtube_player_flutter: ^9.1.3

dependency_overrides:
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/