name: widgetbook_workspace
description: "Widgetbook workspace for the application."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  aplicativo_flutter:
    path: ../
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  widgetbook: ^3.20.0
  widgetbook_annotation: ^3.9.0
  google_fonts: ^6.3.2

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.16.0

flutter:
  uses-material-design: true
